source: .
destination: ./_site
layouts:     ./_layouts
safe:        true
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
gems:        []
lsi:         true
future:      true
permalink:   pretty
